<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Faker\Factory as Faker;

class AssignmentSeeder extends Seeder
{
    public function run()
    {
        $faker = Faker::create();
        $data = [];
        
        // Retrieve all module IDs and their corresponding names
        $modules = DB::table('modules')->get(['module_id', 'module_name']);

        $assignmentTitles = [
            'Research Paper on ',
            'Case Study on ',
            'Project Report on ',
            'Lab Experiment on ',
            'Field Study on ',
            'Critical Analysis of ',
            'Design and Implementation of ',
            'Exploring the Concepts of ',
            'Evaluation of ',
            'Developing a Prototype of ',
            'Simulation Study of ',
            'Review and Assessment of ',
            'Detailed Study on ',
            'Application of ',
            'Investigation into ',
            'Survey on ',
            'Review of ',
            'Practical Application of ',
            'In-depth Analysis of ',
            'Building a Model for ',
            'Thesis on ',
            'Study of ',
            'Implementation of ',
            'Analysis of ',
            'Review Paper on ',
            'Comparative Study of ',
            'Exploratory Study on ',
            'Feasibility Study of ',
            'Impact Analysis of ',
            'Strategic Review of ',
            'Technical Report on ',
            'Exploratory Analysis of ',
            'Design Project on ',
            'Development of ',
            'Performance Analysis of ',
            'Algorithm Design for ',
            'Experimental Study on ',
            'Behavioral Analysis of ',
            'Architectural Design of ',
            'System Design for ',
            'Evaluation Report on ',
            'Comparative Analysis of ',
            'Review of Theories on ',
            'Case Study Analysis of ',
            'Field Research on ',
            'Investigation Report on ',
            'Synthesis Study of ',
            'Review of Applications in ',
            'Impact Study on ',
            'Review of Techniques in ',
        ];

        // Map module names to their corresponding file paths
        $moduleFilePaths = [
            'Introduction to Computer Science' => '/seeder-media/assignments/Introduction_to_Computer_Science_Example_Assignment.docx',
            'Advanced Mathematics' => '/seeder-media/assignments/Advanced_Mathematics_Example_Assignment.docx',
            'Fundamentals of Physics' => '/seeder-media/assignments/Fundamentals_of_Physics_Example_Assignment.docx',
            'Organic Chemistry' => '/seeder-media/assignments/Organic_Chemistry_Example_Assignment.docx',
            'World History' => '/seeder-media/assignments/World_History_Example_Assignment.docx',
            'Modern Literature' => '/seeder-media/assignments/Modern_Literature_Example_Assignment.docx',
            'Psychology 101' => '/seeder-media/assignments/Psychology_101_Example_Assignment.docx',
            'Principles of Economics' => '/seeder-media/assignments/Principles_of_Economics_Example_Assignment.docx',
            'Software Engineering' => '/seeder-media/assignments/Software_Engineering_Example_Assignment.docx',
            'Data Structures and Algorithms' => '/seeder-media/assignments/Data_Structures_and_Algorithms_Example_Assignment.docx',
            'Calculus I' => '/seeder-media/assignments/Calculus_I_Example_Assignment.docx',
            'Calculus II' => '/seeder-media/assignments/Calculus_II_Example_Assignment.docx',
            'Linear Algebra' => '/seeder-media/assignments/Linear_Algebra_Example_Assignment.docx',
            'Discrete Mathematics' => '/seeder-media/assignments/Discrete_Mathematics_Example_Assignment.docx',
            'Introduction to Programming' => '/seeder-media/assignments/Introduction_to_Programming_Example_Assignment.docx',
            'Object-Oriented Programming' => '/seeder-media/assignments/Object_Oriented_Programming_Example_Assignment.docx',
            'Operating Systems' => '/seeder-media/assignments/Operating_Systems_Example_Assignment.docx',
            'Database Management Systems' => '/seeder-media/assignments/Database_Management_Systems_Example_Assignment.docx',
            'Computer Networks' => '/seeder-media/assignments/Computer_Networks_Example_Assignment.docx',
            'Artificial Intelligence' => '/seeder-media/assignments/Artificial_Intelligence_Example_Assignment.docx',
            'Machine Learning' => '/seeder-media/assignments/Machine_Learning_Example_Assignment.docx',
            'Data Science' => '/seeder-media/assignments/Data_Science_Example_Assignment.docx',
            'Big Data Analytics' => '/seeder-media/assignments/Big_Data_Analytics_Example_Assignment.docx',
            'Cloud Computing' => '/seeder-media/assignments/Cloud_Computing_Example_Assignment.docx',
            'Cybersecurity' => '/seeder-media/assignments/Cybersecurity_Example_Assignment.docx',
            'Human-Computer Interaction' => '/seeder-media/assignments/Human_Computer_Interaction_Example_Assignment.docx',
            'Software Testing' => '/seeder-media/assignments/Software_Testing_Example_Assignment.docx',
            'Digital Logic Design' => '/seeder-media/assignments/Digital_Logic_Design_Example_Assignment.docx',
            'Computer Architecture' => '/seeder-media/assignments/Computer_Architecture_Example_Assignment.docx',
            'Microprocessor Systems' => '/seeder-media/assignments/Microprocessor_Systems_Example_Assignment.docx',
            'Embedded Systems' => '/seeder-media/assignments/Embedded_Systems_Example_Assignment.docx',
            'Mobile Application Development' => '/seeder-media/assignments/Mobile_Application_Development_Example_Assignment.docx',
            'Web Development' => '/seeder-media/assignments/Web_Development_Example_Assignment.docx',
            'Game Development' => '/seeder-media/assignments/Game_Development_Example_Assignment.docx',
            'Computer Graphics' => '/seeder-media/assignments/Computer_Graphics_Example_Assignment.docx',
            'Natural Language Processing' => '/seeder-media/assignments/Natural_Language_Processing_Example_Assignment.docx',
            'Robotics' => '/seeder-media/assignments/Robotics_Example_Assignment.docx',
            'Internet of Things' => '/seeder-media/assignments/Internet_of_Things_Example_Assignment.docx',
            'Blockchain Technology' => '/seeder-media/assignments/Blockchain_Technology_Example_Assignment.docx',
            'Quantum Computing' => '/seeder-media/assignments/Quantum_Computing_Example_Assignment.docx',
            'Renewable Energy Systems' => '/seeder-media/assignments/Renewable_Energy_Systems_Example_Assignment.docx',
            'Environmental Science' => '/seeder-media/assignments/Environmental_Science_Example_Assignment.docx',
            'Biotechnology' => '/seeder-media/assignments/Biotechnology_Example_Assignment.docx',
            'Genetics' => '/seeder-media/assignments/Genetics_Example_Assignment.docx',
            'Molecular Biology' => '/seeder-media/assignments/Molecular_Biology_Example_Assignment.docx',
            'Immunology' => '/seeder-media/assignments/Immunology_Example_Assignment.docx',
            'Neuroscience' => '/seeder-media/assignments/Neuroscience_Example_Assignment.docx',
            'Pharmacology' => '/seeder-media/assignments/Pharmacology_Example_Assignment.docx',
            'Epidemiology' => '/seeder-media/assignments/Epidemiology_Example_Assignment.docx',
            'Public Health' => '/seeder-media/assignments/Public_Health_Example_Assignment.docx',
            'Sociology' => '/seeder-media/assignments/Sociology_Example_Assignment.docx',
            'Anthropology' => '/seeder-media/assignments/Anthropology_Example_Assignment.docx',
            'Political Science' => '/seeder-media/assignments/Political_Science_Example_Assignment.docx',
            'International Relations' => '/seeder-media/assignments/International_Relations_Example_Assignment.docx',
            'Law and Society' => '/seeder-media/assignments/Law_and_Society_Example_Assignment.docx',
            'Criminal Justice' => '/seeder-media/assignments/Criminal_Justice_Example_Assignment.docx',
            'Forensic Science' => '/seeder-media/assignments/Forensic_Science_Example_Assignment.docx',
            'Psychiatry' => '/seeder-media/assignments/Psychiatry_Example_Assignment.docx',
            'Clinical Psychology' => '/seeder-media/assignments/Clinical_Psychology_Example_Assignment.docx',
            'Developmental Psychology' => '/seeder-media/assignments/Developmental_Psychology_Example_Assignment.docx',
            'Educational Psychology' => '/seeder-media/assignments/Educational_Psychology_Example_Assignment.docx',
            'Social Psychology' => '/seeder-media/assignments/Social_Psychology_Example_Assignment.docx',
            'Marketing' => '/seeder-media/assignments/Marketing_Example_Assignment.docx',
            'Finance' => '/seeder-media/assignments/Finance_Example_Assignment.docx',
            'Accounting' => '/seeder-media/assignments/Accounting_Example_Assignment.docx',
            'Management' => '/seeder-media/assignments/Management_Example_Assignment.docx',
            'Entrepreneurship' => '/seeder-media/assignments/Entrepreneurship_Example_Assignment.docx',
            'Human Resource Management' => '/seeder-media/assignments/Human_Resource_Management_Example_Assignment.docx',
            'Operations Management' => '/seeder-media/assignments/Operations_Management_Example_Assignment.docx',
            'Business Analytics' => '/seeder-media/assignments/Business_Analytics_Example_Assignment.docx',
            'Supply Chain Management' => '/seeder-media/assignments/Supply_Chain_Management_Example_Assignment.docx',
            'Information Systems' => '/seeder-media/assignments/Information_Systems_Example_Assignment.docx',
            'Econometrics' => '/seeder-media/assignments/Econometrics_Example_Assignment.docx',
            'Macroeconomics' => '/seeder-media/assignments/Macroeconomics_Example_Assignment.docx',
            'Microeconomics' => '/seeder-media/assignments/Microeconomics_Example_Assignment.docx',
            'Labor Economics' => '/seeder-media/assignments/Labor_Economics_Example_Assignment.docx',
            'Health Economics' => '/seeder-media/assignments/Health_Economics_Example_Assignment.docx',
            'Urban Planning' => '/seeder-media/assignments/Urban_Planning_Example_Assignment.docx',
            'Architecture' => '/seeder-media/assignments/Architecture_Example_Assignment.docx',
            'Interior Design' => '/seeder-media/assignments/Interior_Design_Example_Assignment.docx',
            'Landscape Architecture' => '/seeder-media/assignments/Landscape_Architecture_Example_Assignment.docx',
            'Urban Design' => '/seeder-media/assignments/Urban_Design_Example_Assignment.docx',
            'Civil Engineering' => '/seeder-media/assignments/Civil_Engineering_Example_Assignment.docx',
            'Mechanical Engineering' => '/seeder-media/assignments/Mechanical_Engineering_Example_Assignment.docx',
            'Electrical Engineering' => '/seeder-media/assignments/Electrical_Engineering_Example_Assignment.docx',
            'Chemical Engineering' => '/seeder-media/assignments/Chemical_Engineering_Example_Assignment.docx',
            'Materials Science' => '/seeder-media/assignments/Materials_Science_Example_Assignment.docx',
            'Aeronautical Engineering' => '/seeder-media/assignments/Aeronautical_Engineering_Example_Assignment.docx',
            'Biomedical Engineering' => '/seeder-media/assignments/Biomedical_Engineering_Example_Assignment.docx',
            'Nuclear Engineering' => '/seeder-media/assignments/Nuclear_Engineering_Example_Assignment.docx',
            'Marine Engineering' => '/seeder-media/assignments/Marine_Engineering_Example_Assignment.docx',
            'Agricultural Engineering' => '/seeder-media/assignments/Agricultural_Engineering_Example_Assignment.docx',
            'Food Science' => '/seeder-media/assignments/Food_Science_Example_Assignment.docx',
            'Nutrition' => '/seeder-media/assignments/Nutrition_Example_Assignment.docx',
            'Sports Science' => '/seeder-media/assignments/Sports_Science_Example_Assignment.docx',
            'Kinesiology' => '/seeder-media/assignments/Kinesiology_Example_Assignment.docx',
            'Music Theory' => '/seeder-media/assignments/Music_Theory_Example_Assignment.docx',
            'Music Performance' => '/seeder-media/assignments/Music_Performance_Example_Assignment.docx',
            'Theater Arts' => '/seeder-media/assignments/Theater_Arts_Example_Assignment.docx',
            'Film Studies' => '/seeder-media/assignments/Film_Studies_Example_Assignment.docx',
            'Art History' => '/seeder-media/assignments/Art_History_Example_Assignment.docx',
            'Visual Arts' => '/seeder-media/assignments/Visual_Arts_Example_Assignment.docx',
            'Graphic Design' => '/seeder-media/assignments/Graphic_Design_Example_Assignment.docx',
        ];

        for ($i = 0; $i < 500; $i++) { // Assuming we seed 500 assignments
            $module = $faker->randomElement($modules); // Get a random module
            
            $data[] = [
                'module_id' => $module->module_id, // Ensure module_id exists
                'title' => $faker->randomElement($assignmentTitles) . $module->module_name,
                'weightage' => $faker->randomElement([10, 20, 30]),
                'description' => 'This assignment for ' . $module->module_name . ' involves ' . $faker->sentence,
                'due_date' => $faker->dateTimeBetween('now', '+1 year'),
                'file_path' => $moduleFilePaths[$module->module_name] ?? null, // Assign file path based on module name
                'created_at' => now(),
                'updated_at' => now(),
            ];
        }

        DB::table('assignments')->insert($data);
    }
}
